### ISSUE TITLE
not logging in

### ISSUE THREAD

**Issue by Adaaks** [petersolimine/tiktok-growth-bot#1]
whenever i try to run node manualLogin.js, it just doesnt do nothing, not even open chromnium, i installed npm, node and python

**Comment by galinickel** [comment]
also experiencing this, is there any solution?

**Comment by petersolimine** [comment]
Hey! I didn’t realize people were going to try this out. I’ll clean up the Readme and explain exactly how this works! 🚀

**Comment by petersolimine** [comment]
Hey, so cookies are stored in private/myCookies, but the folder was ignored by default in .gitignore...
I updated the gitignore and readme. Should be working smoothly. Please feel free to add more issues as they arise!
